### ISSUE TITLE
结合第一次迭代API和UI图以及原型，完善第一次迭代前端

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/front-end#1]
- [ ] 修补你们的潜在问题(github提醒的)

**Comment by MichealWind** [comment]
第一次迭代的发布活动不是一早就有了吗..？还是说API换了所以在API上改一下？

**Comment by MichealWind** [comment]
UI图有换吗

**Comment by iamxiaoyubei** [comment]
是的，UI图和API暂时没有换

**Comment by MichealWind** [comment]
欸所以这个发布活动前端暂时不用改咯2333

**Comment by iamxiaoyubei** [comment]
API文档在document仓库里面，里面就两个参数发生了改变，campus和verified，使用了二进制表示，其他的应该没有，你们根据这个稍微修改一下吧~

**Comment by iamxiaoyubei** [comment]
第一次迭代今晚要结束了，你们这个小修改要快快修改一下哦，根据API文档和技术文档

**Comment by iamxiaoyubei** [comment]
尽快根据API文档(在apiary.io里面查看即可)以及技术文档接上API接口

**Comment by iamxiaoyubei** [comment]
@MichealWind @Juliiii 完成本地以及服务器端的人工测试
@yubei 完成验收测试
