### ISSUE TITLE
第五次前端开发

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/front-end#10]
@MichealWind @Juliiii 
## 页面开发
- [ ] 完善第五次需求文档中**社团的活动管理**相关页面的开发

## API交接：完成**第五次迭代技术文档**中的七个API的前端交接，请于第五次技术文档和API文档获得API的解释
- [ ] List required actApply

- [ ] Delete ActApply By Club

- [ ] Close Activity Apply By Club

- [x] List required activities By Club

- [x] Get detailed activity information

- [x] Modify Activity Info By Manager or Club

- [x] Get The number of Activity Status By Club

请于 6月17日晚23：39（下周日）之前完成，并且确保本地和服务端进行了基本的测试，之后再进行验收测试

我知道你们应该都很忙了(哭笑)，就麻烦大佬们在空闲之余尽可能完成一下，你们俩有时间的时候就都做一点做一点，这也是最后一次迭代了，因为要求要在六月底之前交代码，所以真的辛苦你们了♥

**Comment by Juliiii** [comment]
@iamxiaoyubei 我今天开始做迭代5

**Comment by iamxiaoyubei** [comment]
好的，加油(ง •_•)ง

**Comment by Juliiii** [comment]
@iamxiaoyubei  List required actApply 404

**Comment by iamxiaoyubei** [comment]
@Juliiii 
这三个你按照API来接就好了
List required actApply
Delete ActApply By Club
Close Activity Apply By Club
玄昭还没有测试完部署上去，若API有什么问题就问我

其他的几个API我测试过，应该是ok的。

**Comment by iamxiaoyubei** [comment]
注意，get list的page都是从1开始，若没有list item则会返回204
