### ISSUE TITLE
关于接口的问题

### ISSUE THREAD

**Issue by TXZdream** [SYSU-ActivityPlusPC/front-end#4]
由于本人对微服务的理解并不很透彻，因此小程序和pc端的后台服务器我没法布置到同一个域名下，因此在配置服务器时，使用了如下的安排：
1. 小程序端直接运行在根目录
2. pc端的后台需要在请求地址前加上/api/
3. 跨域暂未支持

**Comment by iamxiaoyubei** [comment]
没事，目前PC和小程序没法共用API，正好。
之后PC后端的API也独立出来即可。
