### ISSUE TITLE
问题：前端发布活动的数据与借口定义不符

### ISSUE THREAD

**Issue by TXZdream** [SYSU-ActivityPlusPC/front-end#5]
前端发布活动时，发送的时间数据包含了具体时间，而后台的代码解析是根据接口而来的日期解析，望修改

**Comment by iamxiaoyubei** [comment]
@wuxuemin 发布活动的各种时间选项，是否需要时分秒时间，还是只需要日期即可。

**Comment by wuxuemin** [comment]
需要小时和分钟

**Comment by iamxiaoyubei** [comment]
需要在后端的时间相关属性中加入小时和分钟

**Comment by TXZdream** [comment]
依据借口文档完成代码，在接口文档修改前，不会对代码进行修改

**Comment by iamxiaoyubei** [comment]
请参照第一次发布活动API文档和技术文档进行修改，谢谢

**Comment by iamxiaoyubei** [comment]
1. activity数据表字段进行了增加，相关的属性说明在技术文档可查看，属性类型和是否空等可查看document根目录下的er model，使用workbench打开即可
2. 发布活动API进行了修正，apiary修改了，以及技术文档中也添加了说明
如果还有什么问题，请反馈~
