### ISSUE TITLE
第四次前端开发

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/front-end#9]
@MichealWind @Juliiii 分配给你们的任务如下，你们内部可以自行分配任务具体完成人员
## 页面开发
- [ ] 完成第四次需求文档中**社团管理**相关页面的开发

## API交接：完成**注册申请，查看社团信息和通知社团**中的七个API的前端交接，请于第四次技术文档和API文档获得API的解释
- [x] PC User List

- [x] Audit PC User By Manager

- [x] Get detailed PC User information

- [ ] Publish a New Message

- [ ] List required messages 

- [ ] Delete Message By Manager 

- [ ] Get detailed message information

请于 6月4日晚23：39之前完成，并且确保本地和服务端进行了基本的测试，之后再进行验收测试

**Comment by iamxiaoyubei** [comment]
@MichealWind @Juliiii 请抓紧完成任务哦，ddl临近了哦

**Comment by Juliiii** [comment]
@iamxiaoyubei 这阵子比较忙，下周末开始看看情况做

**Comment by MichealWind** [comment]
我也，要复习分布式

**Comment by iamxiaoyubei** [comment]
（哭笑）
那你们先忙着吧，把ddl拖后到这周六可否？
@MichealWind 你啥时候考试？

**Comment by iamxiaoyubei** [comment]
emmm,那推到这周日ok不？
其实页面基本完成了的，主要应该是些小细节，然后这些API以前应该也接过一点点，emmm~
主要是怕你们以后时间更少，佳仕也去实习了...
emmm，这是倒数第二次迭代了，这次迭代完成再尽快完成最后一次，就差不多结束了~

**Comment by iamxiaoyubei** [comment]
再催下 @Juliiii  @MichealWind  大佬们
